name: Build and Deploy
on:
    push:
        branches: [main]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  persist-credentials: false
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              id: pnpm-install
              with:
                  run_install: false
            - name: Build
              run: |
                  npm -v
                  pnpm -v
                  node --trace-uncaught scripts/init.mjs
                  node --trace-uncaught scripts/build.mjs github
            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  token: ${{ secrets.ACCESS_TOKEN }}
                  branch: gh-pages
                  folder: dist
                  force: true
