/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCol: typeof import('vant/es')['Col']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanNoticeBar: typeof import('vant/es')['NoticeBar']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanProgress: typeof import('vant/es')['Progress']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanRow: typeof import('vant/es')['Row']
    VanSkeleton: typeof import('vant/es')['Skeleton']
    VanSlider: typeof import('vant/es')['Slider']
    VanSpace: typeof import('vant/es')['Space']
    VanSticky: typeof import('vant/es')['Sticky']
    VanSubmitBar: typeof import('vant/es')['SubmitBar']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}

// For TSX support
declare global {
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const VanActionSheet: typeof import('vant/es')['ActionSheet']
  const VanButton: typeof import('vant/es')['Button']
  const VanCell: typeof import('vant/es')['Cell']
  const VanCellGroup: typeof import('vant/es')['CellGroup']
  const VanCol: typeof import('vant/es')['Col']
  const VanConfigProvider: typeof import('vant/es')['ConfigProvider']
  const VanField: typeof import('vant/es')['Field']
  const VanForm: typeof import('vant/es')['Form']
  const VanGrid: typeof import('vant/es')['Grid']
  const VanGridItem: typeof import('vant/es')['GridItem']
  const VanIcon: typeof import('vant/es')['Icon']
  const VanImage: typeof import('vant/es')['Image']
  const VanList: typeof import('vant/es')['List']
  const VanNavBar: typeof import('vant/es')['NavBar']
  const VanNoticeBar: typeof import('vant/es')['NoticeBar']
  const VanPicker: typeof import('vant/es')['Picker']
  const VanPopup: typeof import('vant/es')['Popup']
  const VanProgress: typeof import('vant/es')['Progress']
  const VanPullRefresh: typeof import('vant/es')['PullRefresh']
  const VanRow: typeof import('vant/es')['Row']
  const VanSkeleton: typeof import('vant/es')['Skeleton']
  const VanSlider: typeof import('vant/es')['Slider']
  const VanSpace: typeof import('vant/es')['Space']
  const VanSticky: typeof import('vant/es')['Sticky']
  const VanSubmitBar: typeof import('vant/es')['SubmitBar']
  const VanSwipe: typeof import('vant/es')['Swipe']
  const VanSwipeItem: typeof import('vant/es')['SwipeItem']
  const VanTab: typeof import('vant/es')['Tab']
  const VanTabbar: typeof import('vant/es')['Tabbar']
  const VanTabbarItem: typeof import('vant/es')['TabbarItem']
  const VanTabs: typeof import('vant/es')['Tabs']
}